package enrich

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestWriteAnalysis_CreatesFiles(t *testing.T) {
	dir := t.TempDir()
	content := "## Overview\nThis module manages networking."

	path, err := WriteAnalysis(dir, content)
	if err != nil {
		t.Fatalf("WriteAnalysis: %v", err)
	}
	if path != filepath.Join(dir, "ANALYSIS.md") {
		t.Errorf("unexpected path: %s", path)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading ANALYSIS.md: %v", err)
	}
	if !strings.Contains(string(data), "## Overview") {
		t.Error("ANALYSIS.md missing expected content")
	}
}

func TestWriteAnalysis_InjectsIntoReadme(t *testing.T) {
	dir := t.TempDir()
	readmePath := filepath.Join(dir, "README.md")
	existing := "# My Module\n\n<!-- BEGIN_TF_DOCS -->\nautogenerated\n<!-- END_TF_DOCS -->\n"
	if err := os.WriteFile(readmePath, []byte(existing), 0o600); err != nil {
		t.Fatalf("writing README.md: %v", err)
	}

	content := "## Overview\nAnalysis content."
	if _, err := WriteAnalysis(dir, content); err != nil {
		t.Fatalf("WriteAnalysis: %v", err)
	}

	readme, err := os.ReadFile(readmePath)
	if err != nil {
		t.Fatalf("reading README.md: %v", err)
	}
	out := string(readme)
	if !strings.Contains(out, analysisBeginMarker) {
		t.Error("README.md missing begin marker")
	}
	if !strings.Contains(out, analysisEndMarker) {
		t.Error("README.md missing end marker")
	}
	if !strings.Contains(out, "Analysis content.") {
		t.Error("README.md missing analysis content")
	}
	// Original content must be preserved.
	if !strings.Contains(out, "autogenerated") {
		t.Error("README.md original content was lost")
	}
}

func TestWriteAnalysis_Idempotent(t *testing.T) {
	dir := t.TempDir()
	readmePath := filepath.Join(dir, "README.md")
	if err := os.WriteFile(readmePath, []byte("# Mod\n"), 0o600); err != nil {
		t.Fatalf("writing README.md: %v", err)
	}

	content := "## Overview\nFirst run."
	if _, err := WriteAnalysis(dir, content); err != nil {
		t.Fatalf("first WriteAnalysis: %v", err)
	}

	content2 := "## Overview\nSecond run."
	if _, err := WriteAnalysis(dir, content2); err != nil {
		t.Fatalf("second WriteAnalysis: %v", err)
	}

	readme, _ := os.ReadFile(readmePath)
	out := string(readme)
	if strings.Count(out, analysisBeginMarker) != 1 {
		t.Errorf("expected exactly one begin marker, got:\n%s", out)
	}
	if strings.Contains(out, "First run.") {
		t.Error("first run content should have been replaced")
	}
	if !strings.Contains(out, "Second run.") {
		t.Error("second run content should be present")
	}
}

func TestWriteAnalysis_EmptyContent(t *testing.T) {
	dir := t.TempDir()
	path, err := WriteAnalysis(dir, "")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if path != "" {
		t.Errorf("expected empty path for empty content, got %s", path)
	}
}
