package terragrunt

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// WorkloadInputs holds the shared (non-environment-specific) input values
// for one workload that will be written into _envcommon/<workload>.hcl.
type WorkloadInputs struct {
	// Name is the workload identifier, e.g. "networking" or "compute".
	Name string
	// ModuleSource is the relative path or registry address of the module.
	ModuleSource string
	// Inputs is a map of input name → HCL literal value (already quoted if string).
	Inputs map[string]string
}

// envcommonTemplate is a minimal _envcommon/<workload>.hcl file.
// Each environment's terragrunt.hcl will read_terragrunt_config this file
// and merge environment-specific overrides on top.
const envcommonTemplate = `# _envcommon/%s.hcl — generated by azlift
# Shared inputs inherited by all environments for the %s workload.

locals {
  # Merge env-level variables loaded by the caller.
  environment = local.env_vars.locals.environment
}

inputs = {
%s}
`

// GenerateEnvcommon writes one _envcommon/<workload>.hcl for each entry in
// workloads into <outputDir>/_envcommon/.
func GenerateEnvcommon(outputDir string, workloads []WorkloadInputs) error {
	dir := filepath.Join(outputDir, "_envcommon")
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return fmt.Errorf("creating _envcommon dir: %w", err)
	}

	for _, w := range workloads {
		if err := writeEnvcommonFile(dir, w); err != nil {
			return err
		}
	}
	return nil
}

func writeEnvcommonFile(dir string, w WorkloadInputs) error {
	var sb strings.Builder
	// Sort inputs for deterministic output.
	keys := make([]string, 0, len(w.Inputs))
	for k := range w.Inputs {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, k := range keys {
		fmt.Fprintf(&sb, "  %s = %s\n", k, w.Inputs[k])
	}

	content := fmt.Sprintf(envcommonTemplate, w.Name, w.Name, sb.String())
	dest := filepath.Join(dir, w.Name+".hcl")
	if err := os.WriteFile(dest, []byte(content), 0o600); err != nil {
		return fmt.Errorf("writing %s: %w", dest, err)
	}
	return nil
}

// DefaultWorkloads derives a WorkloadInputs slice from the grouped output
// file names produced by the refine stage. Each grouped file (e.g.
// "networking.tf") becomes a workload named after its stem.
func DefaultWorkloads(groupedFileNames []string, moduleBaseDir string) []WorkloadInputs {
	var out []WorkloadInputs
	for _, name := range groupedFileNames {
		stem := strings.TrimSuffix(filepath.Base(name), ".tf")
		// Skip scaffold files that are not workload modules.
		switch stem {
		case "backend", "versions", "providers", "variables", "locals":
			continue
		}
		out = append(out, WorkloadInputs{
			Name:         stem,
			ModuleSource: filepath.Join(moduleBaseDir, stem),
			Inputs:       map[string]string{},
		})
	}
	return out
}
