package terragrunt

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Environment describes one deployment tier.
type Environment struct {
	// Name is the environment identifier, e.g. "prod", "staging", "dev".
	Name string
	// SubscriptionID is the Azure subscription for this environment (may be empty).
	SubscriptionID string
	// Tags is a map of tag key → value applied to all resources in this env.
	Tags map[string]string
}

// DefaultEnvironments returns the standard three-tier set with empty
// subscription IDs (filled in during BOOTSTRAP).
func DefaultEnvironments() []Environment {
	return []Environment{
		{Name: "prod", Tags: map[string]string{"environment": "prod"}},
		{Name: "staging", Tags: map[string]string{"environment": "staging"}},
		{Name: "dev", Tags: map[string]string{"environment": "dev"}},
	}
}

// envHCLTemplate is the env.hcl placed at <env>/ root.
const envHCLTemplate = `# %s/env.hcl — generated by azlift

locals {
  environment     = "%s"
  subscription_id = "%s"
  tags = {
%s  }
}
`

// workloadTGTemplate is the terragrunt.hcl placed at <env>/<workload>/.
const workloadTGTemplate = `# %s/%s/terragrunt.hcl — generated by azlift

locals {
  env_vars    = read_terragrunt_config(find_in_parent_folders("env.hcl"))
  common_vars = read_terragrunt_config(find_in_parent_folders("_envcommon/%s.hcl"))
}

terraform {
  source = "${get_repo_root()}/modules/%s"
}

inputs = merge(
  local.common_vars.inputs,
  {
    environment = local.env_vars.locals.environment
    tags        = local.env_vars.locals.tags
  },
)
`

// GenerateEnvironments writes the per-environment directory tree under outputDir:
//
//	<env>/env.hcl
//	<env>/<workload>/terragrunt.hcl   (one per workload)
func GenerateEnvironments(outputDir string, envs []Environment, workloads []WorkloadInputs) error {
	for _, env := range envs {
		envDir := filepath.Join(outputDir, env.Name)
		if err := os.MkdirAll(envDir, 0o750); err != nil {
			return fmt.Errorf("creating %s: %w", envDir, err)
		}

		if err := writeEnvHCL(envDir, env); err != nil {
			return err
		}

		for _, w := range workloads {
			if err := writeWorkloadTG(envDir, env.Name, w); err != nil {
				return err
			}
		}
	}
	return nil
}

func writeEnvHCL(envDir string, env Environment) error {
	var tagsSB strings.Builder
	// Sort tags for determinism.
	keys := make([]string, 0, len(env.Tags))
	for k := range env.Tags {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(&tagsSB, "    %s = \"%s\"\n", k, env.Tags[k])
	}

	sub := env.SubscriptionID
	if sub == "" {
		sub = "<subscription_id>"
	}

	content := fmt.Sprintf(envHCLTemplate, env.Name, env.Name, sub, tagsSB.String())
	dest := filepath.Join(envDir, "env.hcl")
	return os.WriteFile(dest, []byte(content), 0o600)
}

func writeWorkloadTG(envDir, envName string, w WorkloadInputs) error {
	wDir := filepath.Join(envDir, w.Name)
	if err := os.MkdirAll(wDir, 0o750); err != nil {
		return fmt.Errorf("creating workload dir %s: %w", wDir, err)
	}

	content := fmt.Sprintf(workloadTGTemplate, envName, w.Name, w.Name, w.Name)
	dest := filepath.Join(wDir, "terragrunt.hcl")
	return os.WriteFile(dest, []byte(content), 0o600)
}
