package terragrunt

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// envStackTemplate is the per-environment terragrunt.hcl template.
const envStackTemplate = `# envs/%s/terragrunt.hcl — generated by azlift

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

terraform {
  source = "../../module"
}

inputs = {
%s}
`

// writeEnvStack writes envs/<env>/terragrunt.hcl.
// rgInputs maps variable name → RG value specific to this environment.
func writeEnvStack(envDir, env string, rgInputs map[string]string) error {
	var sb strings.Builder
	fmt.Fprintf(&sb, "  environment = %q\n", env)

	for _, name := range sortedKeys(rgInputs) {
		fmt.Fprintf(&sb, "  %-30s = %q\n", name, rgInputs[name])
	}

	content := fmt.Sprintf(envStackTemplate, env, sb.String())
	dest := filepath.Join(envDir, "terragrunt.hcl")
	if err := os.WriteFile(dest, []byte(content), 0o600); err != nil {
		return fmt.Errorf("writing %s: %w", dest, err)
	}
	return nil
}
