package terragrunt

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/c4a8-azure/azlift/internal/refine"
)

// moduleResult carries data extracted while building the module/ directory,
// used by the root.hcl and env stack generators.
type moduleResult struct {
	// RGLocals maps local name → original RG value extracted from the source
	// locals.tf (e.g. "resource_group_name" → "rg-myapp-prod").
	RGLocals map[string]string
	// Location is the Azure location default from variables.tf.
	Location string
}

// skipInModule are file base names that Terragrunt manages via generate blocks
// in root.hcl, so they must not be copied into module/.
var skipInModule = map[string]bool{
	"backend.tf":   true,
	"providers.tf": true,
}

// rgLocalNameRe matches resource_group_name and resource_group_name_NNN locals.
var rgLocalNameRe = regexp.MustCompile(`^resource_group_name(_\d+)?$`)

// rgLocalLineRe matches a resource_group_name* = "..." line in a locals block.
var rgLocalLineRe = regexp.MustCompile(`(?m)^[ \t]*resource_group_name(_\d+)?\s*=\s*"[^"]*"[ \t]*\n?`)

// rgLocalRefRe matches local.resource_group_name and local.resource_group_name_NNN.
var rgLocalRefRe = regexp.MustCompile(`\blocal\.(resource_group_name(?:_\d+)?)\b`)

// writeModule copies the refined module files into moduleDir, promoting
// resource_group_name from a local to an input variable and adding the
// environment variable. Returns extracted values needed by the env stacks.
func writeModule(files []*refine.ParsedFile, moduleDir string) (moduleResult, error) {
	result := moduleResult{RGLocals: map[string]string{}}

	// Pass 1 — collect RG local values and location from the in-memory ASTs.
	for _, pf := range files {
		switch filepath.Base(pf.Path) {
		case "locals.tf":
			for _, block := range refine.Blocks(pf, "locals") {
				for name, attr := range block.Body().Attributes() {
					if rgLocalNameRe.MatchString(name) {
						val := strings.TrimSpace(string(attr.Expr().BuildTokens(nil).Bytes()))
						result.RGLocals[name] = strings.Trim(val, `"`)
					}
				}
			}
		case "variables.tf":
			for _, block := range refine.Blocks(pf, "variable") {
				if len(block.Labels()) > 0 && block.Labels()[0] == "location" {
					if attr := block.Body().GetAttribute("default"); attr != nil {
						val := strings.TrimSpace(string(attr.Expr().BuildTokens(nil).Bytes()))
						result.Location = strings.Trim(val, `"`)
					}
				}
			}
		}
	}

	// Pass 2 — transform and write each file to moduleDir.
	for _, pf := range files {
		base := filepath.Base(pf.Path)
		if skipInModule[base] {
			continue
		}

		raw, err := os.ReadFile(pf.Path)
		if err != nil {
			return result, fmt.Errorf("reading %s: %w", base, err)
		}
		content := string(raw)

		switch base {
		case "locals.tf":
			// Remove resource_group_name locals (promoted to variables).
			content = rgLocalLineRe.ReplaceAllString(content, "")
			// Wire environment tag to var.environment.
			content = patchCommonTagsEnvironment(content)
		case "variables.tf":
			content = addModuleVariables(content, result.RGLocals)
		default:
			// Rewrite local.resource_group_name* → var.resource_group_name*.
			content = rgLocalRefRe.ReplaceAllString(content, `var.$1`)
		}

		dest := filepath.Join(moduleDir, base)
		if err := os.WriteFile(dest, []byte(content), 0o600); err != nil {
			return result, fmt.Errorf("writing %s: %w", dest, err)
		}
	}

	return result, nil
}

// patchCommonTagsEnvironment replaces `environment = ""` with
// `environment = var.environment` inside the common_tags local.
// This is safe because the only place `environment = ""` appears in locals.tf
// is inside the common_tags map generated by NormaliseTags.
func patchCommonTagsEnvironment(content string) string {
	return strings.ReplaceAll(content, `environment = ""`, `environment = var.environment`)
}

// addModuleVariables appends variable declarations for environment and each
// resource_group_name* local that was promoted to a variable.
func addModuleVariables(content string, rgLocals map[string]string) string {
	var sb strings.Builder
	sb.WriteString(content)

	if !strings.Contains(content, `variable "environment"`) {
		sb.WriteString(`
variable "environment" {
  description = "Deployment environment (e.g. prod, dev, staging)."
  type        = string
}
`)
	}

	for _, name := range sortedKeys(rgLocals) {
		if !strings.Contains(content, fmt.Sprintf(`variable "%s"`, name)) {
			sb.WriteString(fmt.Sprintf(`
variable "%s" {
  description = "Azure resource group name."
  type        = string
}
`, name))
		}
	}

	return sb.String()
}
