package terragrunt

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/c4a8-azure/azlift/internal/refine"
)

// moduleResult carries data extracted while building the module/ directory,
// used by the root.hcl and env stack generators.
type moduleResult struct {
	// RGLocals maps variable name → default RG value extracted from variables.tf
	// (e.g. "resource_group_name" → "rg-myapp-prod").
	RGLocals map[string]string
	// Location is the Azure location default from variables.tf.
	Location string
}

// skipInModule are file base names that Terragrunt manages via generate blocks
// in root.hcl, so they must not be copied into module/.
var skipInModule = map[string]bool{
	"backend.tf":   true,
	"providers.tf": true,
}

// rgVarNameRe matches variable names resource_group_name and resource_group_name_NNN.
var rgVarNameRe = regexp.MustCompile(`^resource_group_name(_\d+)?$`)

// writeModule copies the refined module files into moduleDir, adding the
// environment input variable and wiring common_tags to use it.
// Returns extracted default values needed by the env stack generators.
//
// The refine stage already promotes resource_group_name to a variable block
// (alwaysVariable) and rewrites resource references to var.resource_group_name,
// so no local→var promotion is needed here.
func writeModule(files []*refine.ParsedFile, moduleDir string) (moduleResult, error) {
	result := moduleResult{RGLocals: map[string]string{}}

	// Pass 1 — collect RG default values and location from variables.tf.
	for _, pf := range files {
		if filepath.Base(pf.Path) != "variables.tf" {
			continue
		}
		for _, block := range refine.Blocks(pf, "variable") {
			if len(block.Labels()) == 0 {
				continue
			}
			name := block.Labels()[0]
			def := block.Body().GetAttribute("default")
			if def == nil {
				continue
			}
			val := strings.Trim(strings.TrimSpace(string(def.Expr().BuildTokens(nil).Bytes())), `"`)

			switch {
			case rgVarNameRe.MatchString(name):
				result.RGLocals[name] = val
			case name == "location":
				result.Location = val
			}
		}
	}

	// Pass 2 — transform and write each file to moduleDir.
	for _, pf := range files {
		base := filepath.Base(pf.Path)
		if skipInModule[base] {
			continue
		}

		raw, err := os.ReadFile(pf.Path)
		if err != nil {
			return result, fmt.Errorf("reading %s: %w", base, err)
		}
		content := string(raw)

		switch base {
		case "locals.tf":
			// Wire the environment tag in common_tags to var.environment.
			content = patchCommonTagsEnvironment(content)
		case "variables.tf":
			// Add variable "environment" so each env stack can pass a value.
			content = addEnvironmentVariable(content)
		}
		// Resource files need no transformation: the refine stage already
		// wrote var.resource_group_name (alwaysVariable) into every resource block.

		dest := filepath.Join(moduleDir, base)
		if err := os.WriteFile(dest, []byte(content), 0o600); err != nil {
			return result, fmt.Errorf("writing %s: %w", dest, err)
		}
	}

	return result, nil
}

// patchCommonTagsEnvironment replaces `environment = ""` with
// `environment = var.environment` inside the common_tags local.
// This is safe because the only place `environment = ""` appears in locals.tf
// is inside the common_tags map generated by NormaliseTags.
func patchCommonTagsEnvironment(content string) string {
	return strings.ReplaceAll(content, `environment = ""`, `environment = var.environment`)
}

// addEnvironmentVariable appends a variable "environment" block to the content
// of variables.tf if one is not already present.
func addEnvironmentVariable(content string) string {
	if strings.Contains(content, `variable "environment"`) {
		return content
	}
	return content + `
variable "environment" {
  description = "Deployment environment (e.g. prod, dev, staging)."
  type        = string
}
`
}
