package terragrunt

import (
	"fmt"
	"os"
	"path/filepath"
)

// rootHCLTemplate is the canonical root.hcl for an azlift Terragrunt project.
// Backend placeholder values (FILL_IN_*) are replaced by azlift bootstrap.
const rootHCLTemplate = `# root.hcl — generated by azlift
# Run 'azlift bootstrap' to populate the backend configuration.

remote_state {
  backend = "azurerm"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
  config = {
    resource_group_name  = "FILL_IN_BACKEND_RG"
    storage_account_name = "FILL_IN_STORAGE_ACCOUNT"
    container_name       = "tfstate"
    key                  = "${path_relative_to_include()}/terraform.tfstate"
    use_azuread_auth     = true
  }
}

generate "provider" {
  path      = "providers.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<-EOF
    provider "azurerm" {
      features {}
      storage_use_azuread = true
    }
  EOF
}

inputs = {
  location = "%s"
}
`

// writeRoot generates root.hcl in outputDir using the given Azure location.
func writeRoot(outputDir, location string) error {
	if location == "" {
		location = "westeurope"
	}
	content := fmt.Sprintf(rootHCLTemplate, location)
	dest := filepath.Join(outputDir, "root.hcl")
	if err := os.WriteFile(dest, []byte(content), 0o600); err != nil {
		return fmt.Errorf("writing root.hcl: %w", err)
	}
	return nil
}
