// Package terragrunt implements Terragrunt layout generation for the
// --mode terragrunt output of the azlift refine stage.
//
// The generated layout follows the standard DRY multi-environment pattern:
//
//	<output>/
//	  terragrunt.hcl          ← root config (this package, issue #34)
//	  _envcommon/             ← shared inputs (issue #35)
//	  dev/                    ← per-env directories (issue #36)
//	  staging/
//	  prod/
package terragrunt

import (
	"fmt"
	"os"
	"path/filepath"
)

// RootConfig holds values used when generating the root terragrunt.hcl.
type RootConfig struct {
	// AzurermVersion is the ~> constraint for the azurerm provider, e.g. "4.0".
	AzurermVersion string
	// BackendResourceGroup is the state storage resource group.
	BackendResourceGroup string
	// BackendStorageAccount is the state storage account name.
	BackendStorageAccount string
	// BackendContainer is the blob container for state files.
	BackendContainer string
}

// DefaultRootConfig returns sensible defaults (placeholder values replaced by
// BOOTSTRAP at a later stage).
func DefaultRootConfig() RootConfig {
	return RootConfig{
		AzurermVersion:        "4.0",
		BackendResourceGroup:  "rg-tfstate",
		BackendStorageAccount: "sttfstate",
		BackendContainer:      "tfstate",
	}
}

// rootTemplate is the canonical root terragrunt.hcl template.
// It uses Terragrunt's built-in functions so it is valid HCL / Terragrunt
// without the Go text/template engine introducing extra escaping complexity.
const rootTemplate = `# Root terragrunt.hcl — generated by azlift
# Edit backend values after running ` + "`" + `azlift bootstrap` + "`" + `.

locals {
  env_vars = read_terragrunt_config(find_in_parent_folders("env.hcl"))
  env      = local.env_vars.locals.environment
}

remote_state {
  backend = "azurerm"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
  config = {
    resource_group_name  = "%s"
    storage_account_name = "%s"
    container_name       = "%s"
    key                  = "${path_relative_to_include()}/terraform.tfstate"
  }
}

generate "provider" {
  path      = "providers.tf"
  if_exists = "overwrite_terragrunt"
  contents  = <<EOF
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> %s"
    }
  }
}

provider "azurerm" {
  features {}
}
EOF
}
`

// GenerateRoot writes the root terragrunt.hcl to outputDir.
func GenerateRoot(outputDir string, cfg RootConfig) error {
	if err := os.MkdirAll(outputDir, 0o750); err != nil {
		return fmt.Errorf("creating output dir: %w", err)
	}

	content := fmt.Sprintf(rootTemplate,
		cfg.BackendResourceGroup,
		cfg.BackendStorageAccount,
		cfg.BackendContainer,
		cfg.AzurermVersion,
	)

	dest := filepath.Join(outputDir, "terragrunt.hcl")
	if err := os.WriteFile(dest, []byte(content), 0o600); err != nil {
		return fmt.Errorf("writing %s: %w", dest, err)
	}
	return nil
}
