package bootstrap

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestWriteBackend_SameTenant(t *testing.T) {
	dir := t.TempDir()
	cfg := BackendConfig{
		ResourceGroupName:  "rg-tfstate-infra-prod",
		StorageAccountName: "stinfraprod",
		ContainerName:      "tfstate",
		Key:                "infra-prod.tfstate",
		Placeholder:        false,
	}

	if err := WriteBackend(cfg, dir); err != nil {
		t.Fatalf("WriteBackend: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "backend.tf"))
	if err != nil {
		t.Fatalf("reading backend.tf: %v", err)
	}
	content := string(data)

	if !strings.Contains(content, "stinfraprod") {
		t.Error("backend.tf should contain storage account name")
	}
	if !strings.Contains(content, "rg-tfstate-infra-prod") {
		t.Error("backend.tf should contain resource group name")
	}
	if strings.Contains(content, "FILL_IN") {
		t.Error("same-tenant backend.tf should not contain FILL_IN")
	}
}

func TestWriteBackend_CrossTenant_Placeholder(t *testing.T) {
	dir := t.TempDir()
	cfg := BackendConfig{
		ContainerName: "tfstate",
		Key:           "infra-prod.tfstate",
		Placeholder:   true,
	}

	if err := WriteBackend(cfg, dir); err != nil {
		t.Fatalf("WriteBackend: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(dir, "backend.tf"))
	content := string(data)

	if !strings.Contains(content, "FILL_IN") {
		t.Error("cross-tenant backend.tf should contain FILL_IN placeholders")
	}
	if !strings.Contains(content, "bootstrap/") {
		t.Error("cross-tenant backend.tf should mention bootstrap/ module in comment")
	}
}

func TestPatchRootHCL_ReplacesFillIn(t *testing.T) {
	dir := t.TempDir()
	// Write a root.hcl with FILL_IN_* placeholders (as generated by terragrunt.writeRoot).
	initial := `remote_state {
  config = {
    resource_group_name  = "FILL_IN_BACKEND_RG"
    storage_account_name = "FILL_IN_STORAGE_ACCOUNT"
    container_name       = "tfstate"
  }
}
`
	if err := os.WriteFile(filepath.Join(dir, "root.hcl"), []byte(initial), 0o600); err != nil {
		t.Fatalf("setup: %v", err)
	}

	cfg := BackendConfig{
		ResourceGroupName:  "rg-tfstate-myapp",
		StorageAccountName: "sttfstatemyapp",
	}
	if err := PatchRootHCL(dir, cfg); err != nil {
		t.Fatalf("PatchRootHCL: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(dir, "root.hcl"))
	if err != nil {
		t.Fatalf("reading root.hcl: %v", err)
	}
	content := string(data)

	if strings.Contains(content, "FILL_IN") {
		t.Error("root.hcl should not contain FILL_IN placeholders after patching")
	}
	if !strings.Contains(content, "rg-tfstate-myapp") {
		t.Error("root.hcl should contain real resource group name")
	}
	if !strings.Contains(content, "sttfstatemyapp") {
		t.Error("root.hcl should contain real storage account name")
	}
}

func TestStateKey_ModulesMode(t *testing.T) {
	key := stateKey("modules", "my-repo", []string{"prod", "dev"})
	if key != "my-repo.tfstate" {
		t.Errorf("want my-repo.tfstate, got %s", key)
	}
}

func TestStateKey_TerragruntMode(t *testing.T) {
	key := stateKey("terragrunt", "my-repo", []string{"prod", "dev"})
	if key != "envs/prod/terraform.tfstate" {
		t.Errorf("want envs/prod/terraform.tfstate, got %s", key)
	}
}

func TestStateKey_TerragruntMode_CustomPrimaryEnv(t *testing.T) {
	key := stateKey("terragrunt", "my-repo", []string{"staging", "dev"})
	if key != "envs/staging/terraform.tfstate" {
		t.Errorf("want envs/staging/terraform.tfstate, got %s", key)
	}
}

func TestStateKey_DefaultMode(t *testing.T) {
	// Empty mode string behaves like modules.
	key := stateKey("", "my-repo", nil)
	if key != "my-repo.tfstate" {
		t.Errorf("want my-repo.tfstate, got %s", key)
	}
}

func TestWriteBackend_DefaultContainer(t *testing.T) {
	dir := t.TempDir()
	cfg := BackendConfig{
		ResourceGroupName:  "rg-tfstate-test",
		StorageAccountName: "sttest",
		Key:                "test.tfstate",
	}

	if err := WriteBackend(cfg, dir); err != nil {
		t.Fatalf("WriteBackend: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(dir, "backend.tf"))
	if !strings.Contains(string(data), `"tfstate"`) {
		t.Error("backend.tf should default container_name to tfstate")
	}
}
