package bootstrap

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"time"

	"github.com/c4a8-azure/azlift/pkg/config"
)

// CommitConfig holds the parameters for the initial commit into the new repo.
type CommitConfig struct {
	// RepoDir is the local clone path of the newly created repository.
	RepoDir string
	// SourceDir, when non-empty, has its contents copied into RepoDir before staging.
	// Use this to plant the refined Terraform output into the bootstrapped repo.
	SourceDir string
	// SubscriptionID is recorded in the commit message.
	SubscriptionID string
	// AzBootstrapConfig is serialised as .azbootstrap.jsonc alongside the TF.
	AzBootstrapConfig *AzBootstrapConfig
}

// CommitResult holds information about the commit that was created.
type CommitResult struct {
	// Message is the standardised commit message.
	Message string
}

// CommitToRepo performs the initial commit of the refined Terraform output:
//  1. Copies SourceDir contents into RepoDir (if SourceDir is set).
//  2. Writes .azbootstrap.jsonc to repoDir (if config provided).
//  3. git add -A.
//  4. git commit with a standardised message.
func CommitToRepo(ctx context.Context, cfg CommitConfig) (CommitResult, error) {
	// 1. Copy refined output into the repo.
	if cfg.SourceDir != "" {
		if err := copyDirContents(cfg.SourceDir, cfg.RepoDir); err != nil {
			return CommitResult{}, fmt.Errorf("copying source to repo: %w", err)
		}
	}

	// 2. Write .azbootstrap.jsonc.
	if cfg.AzBootstrapConfig != nil {
		if err := writeAzBootstrapConfig(cfg.RepoDir, cfg.AzBootstrapConfig); err != nil {
			return CommitResult{}, err
		}
	}

	// 3. Stage all files.
	if err := gitRun(ctx, cfg.RepoDir, "add", "-A"); err != nil {
		return CommitResult{}, fmt.Errorf("git add: %w", err)
	}

	// 3. Commit.
	message := buildCommitMessage(cfg.SubscriptionID)
	if err := gitRun(ctx, cfg.RepoDir, "commit", "--message", message); err != nil {
		return CommitResult{}, fmt.Errorf("git commit: %w", err)
	}

	return CommitResult{Message: message}, nil
}

// gitRun executes a git command in dir and returns a combined error on failure.
func gitRun(ctx context.Context, dir string, args ...string) error {
	cmd := exec.CommandContext(ctx, "git", args...) //nolint:gosec // git is a system tool
	cmd.Dir = dir
	var out bytes.Buffer
	cmd.Stdout = &out
	cmd.Stderr = &out
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("git %v: %w\n%s", args, err, out.String())
	}
	return nil
}

// buildCommitMessage returns the standardised initial commit message.
func buildCommitMessage(subscriptionID string) string {
	ts := time.Now().UTC().Format("2006-01-02")
	return fmt.Sprintf(
		"chore: initial Terraform generated by azlift v%s\n\nSource subscription: %s\nDate: %s",
		config.Version, subscriptionID, ts,
	)
}

// writeAzBootstrapConfig serialises cfg to <repoDir>/.azbootstrap.jsonc.
func writeAzBootstrapConfig(repoDir string, cfg *AzBootstrapConfig) error {
	data, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return fmt.Errorf("serialising .azbootstrap.jsonc: %w", err)
	}
	dest := filepath.Join(repoDir, ".azbootstrap.jsonc")
	if err := os.WriteFile(dest, data, 0o600); err != nil {
		return fmt.Errorf("writing .azbootstrap.jsonc: %w", err)
	}
	return nil
}
