package export

import (
	"strings"
)

// DefaultExcludedTypes contains resource types that should never be exported
// to Terraform — they are either managed out-of-band, unsupported by the
// azurerm provider, or create noise without value.
var DefaultExcludedTypes = []string{
	"microsoft.insights/diagnosticsettings",              // diagnostic settings — typically managed per-workload
	"microsoft.authorization/locks",                      // resource locks — managed separately per policy
	"microsoft.authorization/roleassignments",            // role assignments — managed by platform team
	"microsoft.authorization/roledefinitions",            // custom role definitions — platform-owned
	"microsoft.security/assessments",                     // security centre assessments — read-only
	"microsoft.security/pricings",                        // defender plans — subscription-level config
	"microsoft.alertsmanagement/smartdetectoralertrules", // auto-generated alert rules
	"microsoft.operationalinsights/querypacks",           // auto-generated by Azure Monitor
}

// ExclusionList decides which resources to skip before export.
type ExclusionList struct {
	// types holds normalised (lowercase) resource type strings.
	types map[string]struct{}
}

// NewExclusionList builds a list from the default types plus any extras.
func NewExclusionList(extraTypes []string) *ExclusionList {
	el := &ExclusionList{types: make(map[string]struct{}, len(DefaultExcludedTypes)+len(extraTypes))}
	for _, t := range DefaultExcludedTypes {
		el.types[strings.ToLower(t)] = struct{}{}
	}
	for _, t := range extraTypes {
		el.types[strings.ToLower(t)] = struct{}{}
	}
	return el
}

// IsExcluded returns true when the resource type should be skipped.
func (el *ExclusionList) IsExcluded(resourceType string) bool {
	_, ok := el.types[strings.ToLower(resourceType)]
	return ok
}

// FilterResources partitions resources into (keep, excluded) slices.
func FilterResources[T interface{ GetType() string }](el *ExclusionList, resources []T) (keep, excluded []T) {
	for _, r := range resources {
		if el.IsExcluded(r.GetType()) {
			excluded = append(excluded, r)
		} else {
			keep = append(keep, r)
		}
	}
	return
}
